const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),os=require('node:os');
const {chromium}=require('C:/Users/User/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve('work'),server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.js':'application/javascript','.html':'text/html','.css':'text/css'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);});
function wav(){const b=Buffer.alloc(44+32000);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(8000,24);b.writeUInt32LE(16000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(32000,40);return b;}
const pause=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{await new Promise(r=>server.listen(0,r));const base='http://localhost:'+server.address().port,profile=fs.mkdtempSync(path.join(os.tmpdir(),'au-18v07-')),errors=[];let browser,activeContext;
try{
 const launch=async()=>{console.log('Opening persistent browser');const context=await chromium.launchPersistentContext(profile,{channel:'msedge',headless:true,viewport:{width:393,height:852},isMobile:true,hasTouch:true});await context.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));activeContext=context;return {context,page};};
 let {context,page}=await launch();console.log('Browser open');await page.goto(base+'/ios-app/site/index.html',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.AU_LOCAL_18?.snapshot);await page.waitForFunction(()=>document.getElementById('localStatus')?.textContent.includes('prête')); 
 console.log('Local ready');
 // Actual picker import, owned storage, then complete browser process shutdown.
 await page.locator('#localImport').setInputFiles({name:'01 - Original.wav',mimeType:'audio/wav',buffer:wav()});await page.waitForFunction(()=>document.getElementById('localCount').textContent.includes('1 morceau'));
 await page.evaluate(async()=>{const state=await AU_LOCAL_18.snapshot(),t=state.tracks[0];window.testTrack=t.id;const db=await AU_LOCAL_18.openStore();await AU_LOCAL_18.transaction(db,['tracks','albums','playlists'],'readwrite',tx=>{tx.objectStore('tracks').put({...t,favorite:true,plain:'Paroles originales',lyrics:{sync_mode:'blocks',lines:['Paroles originales'],times:[0],end_time:2},cover:{blob:new Blob(['pochette'],{type:'image/png'})}});tx.objectStore('albums').put({id:'test-album',name:'Album persistant',ids:[t.id]});tx.objectStore('playlists').put({id:'test-list',name:'Playlist',ids:[t.id]});});db.close();});
 console.log('Closing browser for restart');await context.close();({context,page}=await launch());console.log('Restarted');await page.goto(base+'/ios-app/site/index.html',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.getElementById('localCount')?.textContent.includes('1 morceau'));
 console.log('Reading restored library');const restored=await page.evaluate(async()=>{const s=await AU_LOCAL_18.snapshot(),t=s.tracks[0],db=await AU_LOCAL_18.openStore();let request;await AU_LOCAL_18.transaction(db,['tracks'],'readonly',tx=>request=tx.objectStore('tracks').get(t.id));const raw=request.result;db.close();const tagged=await AU_LOCAL_18.writeTags(t.blob,{...t,album:'Album persistant'},1);window.testZip=await AU_LOCAL_18.zip([{name:'Album/01 - Original.wav',blob:tagged},{name:'Album/paroles.json',blob:new Blob([JSON.stringify(t.lyrics)])},{name:'Album/pochette.png',blob:t.cover.blob}]);return {size:t.blob.size,header:await t.blob.slice(0,4).text(),favorite:t.favorite,lyrics:t.lyrics.lines,cover:await t.cover.blob.text(),album:s.albums[0].ids[0]===t.id,playlist:s.playlists[0].ids[0]===t.id,owned:raw.blob.auOwnedBinary,coverOwned:raw.cover.blob.auOwnedBinary,zipSize:testZip.size};});
 assert.deepEqual({...restored,zipSize:0},{size:32044,header:'RIFF',favorite:true,lyrics:['Paroles originales'],cover:'pochette',album:true,playlist:true,owned:1,coverOwned:1,zipSize:0});assert(restored.zipSize>32044);
 await page.evaluate(async()=>{const s=await AU_LOCAL_18.snapshot(),before=s.tracks.length,original=AU_LOCAL_STORAGE_18.encode;let calls=0;AU_LOCAL_STORAGE_18.encode=async v=>{if(++calls===2)throw Error('injected read failure');return original(v);};try{await AU_LOCAL_18.restoreSnapshot({...s,tracks:[...s.tracks,...s.tracks]});throw Error('Expected failure missing');}catch(e){if(!String(e).includes('injected read failure'))throw e;}finally{AU_LOCAL_STORAGE_18.encode=original;}if((await AU_LOCAL_18.snapshot()).tracks.length!==before)throw Error('Partial import committed');});
 await page.evaluate(async()=>{const s=await AU_LOCAL_18.snapshot();await AU_LOCAL_18.restoreSnapshot({...s,tracks:s.tracks.map(t=>({...t,title:'Copie modifiée'}))});});assert.equal(await page.evaluate(async()=> (await AU_LOCAL_18.snapshot()).tracks.length),2);
 await page.locator('[data-go="local"]').first().click({force:true});await page.locator('.local-track').first().getByRole('button',{name:'Écouter',exact:true}).click();await page.waitForFunction(()=>!document.getElementById('localAudio').paused);assert.equal(await page.locator('#localAudio').evaluate(a=>a.duration),2);
 console.log('Playback checked');await page.locator('[data-go="collection"]').first().click({force:true});await page.evaluate(async()=>{const s=await AU_LOCAL_18.snapshot(),a=document.getElementById('audio');a.src=URL.createObjectURL(s.tracks[0].blob);a.loop=true;await a.play();});
 await page.clock.install();
 // Mask control never pauses audio and requires a decision first.
 await page.getByRole('button',{name:'Masquer temporairement le lecteur',exact:true}).click();assert.equal(await page.locator('.player-dock').isVisible(),true);await page.getByRole('button',{name:'Annuler',exact:true}).click();assert.equal(await page.locator('.player-dock').isVisible(),true);
 await page.getByRole('button',{name:'Masquer temporairement le lecteur',exact:true}).click();await page.getByRole('button',{name:'Jusqu’à la prochaine ouverture du site ou de l’application',exact:true}).click();assert.equal(await page.locator('.player-dock').isVisible(),false);assert.equal(await page.locator('#audio').evaluate(a=>a.paused),false);
 await page.locator('#restoreMobilePlayer').scrollIntoViewIfNeeded();assert.equal(await page.locator('#restoreMobilePlayer').evaluate(n=>{const r=n.getBoundingClientRect();return document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)===n;}),true);await page.locator('#restoreMobilePlayer').click();
 await page.getByRole('button',{name:'Masquer temporairement le lecteur',exact:true}).click();const input=page.locator('.au-mobile-player-dialog input');for(const invalid of ['0','61','1.5']){await input.fill(invalid);await page.getByRole('button',{name:'Masquer pendant la durée choisie'}).click();assert.equal(await page.locator('.player-dock').isVisible(),true);}
 await input.fill('1');await page.getByRole('button',{name:'Masquer pendant la durée choisie'}).click();assert.equal(await page.locator('.player-dock').isVisible(),false);await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.documentElement.classList.contains('au-mobile-player-hidden'));
 await page.clock.fastForward(60001);assert.equal(await page.locator('.player-dock').isVisible(),true);await page.clock.uninstall?.();
 await page.getByRole('button',{name:'Masquer temporairement le lecteur',exact:true}).click();await page.getByRole('button',{name:'Jusqu’à la prochaine ouverture du site ou de l’application',exact:true}).click();console.log('Closing browser for restart');await context.close();({context,page}=await launch());console.log('Restarted');await page.goto(base+'/ios-app/site/index.html',{waitUntil:'domcontentloaded'});await page.waitForSelector('.au-mobile-player-close');assert.equal(await page.locator('.player-dock').isVisible(),true);
 await page.waitForFunction(()=>document.getElementById('localCount')?.textContent.includes('2 morceaux'));
 await page.evaluate(async()=>{const db=await AU_LOCAL_18.openStore();let r;await AU_LOCAL_18.transaction(db,['tracks'],'readonly',tx=>r=tx.objectStore('tracks').getAll());const t=r.result.find(t=>t.title==='Original');new Uint8Array(t.blob.chunks[0])[0]^=1;await AU_LOCAL_18.transaction(db,['tracks'],'readwrite',tx=>tx.objectStore('tracks').put(t));db.close();});await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.getElementById('localCount')?.textContent.includes('2 morceaux'));
 await page.locator('[data-go="local"]').first().click({force:true});await page.getByRole('button',{name:'Rattacher le fichier audio',exact:true}).click();await page.locator('dialog[open] input[type=file]').setInputFiles({name:'Original.wav',mimeType:'audio/wav',buffer:wav()});await page.waitForFunction(()=>!document.querySelector('dialog[open]'));assert.deepEqual(await page.evaluate(async()=>{const s=await AU_LOCAL_18.snapshot(),t=s.tracks.find(t=>t.title==='Original');return {cover:await t.cover.blob.text(),favorite:t.favorite,lyrics:t.lyrics.lines[0],header:await t.blob.slice(0,4).text(),album:s.albums.some(a=>a.ids.includes(t.id))};}),{cover:'pochette',favorite:true,lyrics:'Paroles originales',header:'RIFF',album:true});
 await context.close();browser=await chromium.launch({channel:'msedge',headless:true});
 for(const platform of ['desktop-app','android-app','github-sync-import'])for(const width of [320,393,852,1440]){const ctx=await browser.newContext({viewport:{width,height:852},isMobile:width<1000,hasTouch:width<1000});await ctx.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/'+platform+(platform==='github-sync-import'?'':'/site')+'/index.html',{waitUntil:'domcontentloaded'});await pause(300);const expected=platform==='android-app'||platform==='github-sync-import'&&width<1000;assert.equal(await p.locator('.au-mobile-player-close').isVisible(),expected,platform+' '+width);if(!expected&&width===1440){const target=p.locator('.footer button').first();await target.scrollIntoViewIfNeeded();assert.equal(await target.evaluate(n=>{const r=n.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return n===hit||n.contains(hit);}),true,'PC footer access '+platform);}
 if(platform==='github-sync-import'){assert.deepEqual(await p.evaluate(()=>AU_LOCAL_18.snapshot()),{tracks:[],albums:[],playlists:[]});}
 await ctx.close();}
 assert.deepEqual(errors,[]);console.log('PASS 18V07: process restart, picker audio, legacy migration, album/playlist/lyrics/cover, editing, playback and ZIP; mobile duration bounds, cancellation, session reset, persisted deadline, auto return, continued playback; desktop exclusion and web Local gate at four widths.');
}finally{await activeContext?.close();await browser?.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
