const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {startUpdates}=require('../managed-updates.cjs'),{createStore,hash}=require('../version-store.cjs'),{API}=require('../release-api.cjs');
async function fixture(t){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'au-notice-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const base=path.join(dir,'base');fs.mkdirSync(path.join(base,'site'),{recursive:true});fs.writeFileSync(path.join(base,'product.cjs'),'old');fs.writeFileSync(path.join(base,'site/index.html'),'same');const store=createStore(path.join(dir,'updates'),base,'0.2.0');
 let publishedVersion='0.2.1',handler,panels=[],relaunch=0;const hooks={};
 const manifest=()=>({format:1,version:publishedVersion,files:[['product.cjs','new'],['site/index.html','same']].map(([p,b])=>({path:p,bytes:b.length,sha256:hash(Buffer.from(b)),url:`https://github.com/zephiroxDev/avant-usine/releases/download/v${publishedVersion}/au-${hash(Buffer.from(b))}.bin`}))});
 class Window{constructor(){this.closed=false;this.hooks={};this.messages=[];this.webContents={setWindowOpenHandler(){},on(){},send:(_name,state)=>this.messages.push(state),once:(name,fn)=>this.hooks[name]=fn};panels.push(this);}setMenu(){}on(name,fn){this.hooks[name]=fn;}once(name,fn){this.hooks[name]=fn;}isDestroyed(){return this.closed;}show(){}async loadFile(){this.hooks['did-finish-load']();this.hooks['ready-to-show']();}close(){this.hooks.close({preventDefault(){}});this.closed=true;this.hooks.closed();}}
 const electron={BrowserWindow:Window,ipcMain:{handle(_name,fn){handler=fn;},removeHandler(){handler=null;}},net:{fetch:async url=>{
  const body=Buffer.from(JSON.stringify(manifest()));if(url===API)return Response.json([{tag_name:'v'+publishedVersion,assets:[{name:`Avant-Usine-Mise-a-jour-${publishedVersion}.json`,state:'uploaded',digest:'sha256:'+hash(body),browser_download_url:`https://github.com/zephiroxDev/avant-usine/releases/download/v${publishedVersion}/Avant-Usine-Mise-a-jour-${publishedVersion}.json`}]}]);
  if(url.endsWith('.json'))return new Response(body);return new Response('new');
 }},app:{relaunch(){relaunch++;},exit(){}}};
 const control=startUpdates({electron,window:{isDestroyed:()=>false,on:(name,fn)=>hooks[name]=fn},store,current:'0.2.0'});t.after(()=>hooks.closed());for(let n=0;n<20&&!handler;n++)await new Promise(resolve=>setImmediate(resolve));assert(handler);
 return {store,control,panels,choose:choice=>handler({sender:panels.at(-1).webContents},choice),next:version=>publishedVersion=version,relaunch:()=>relaunch};
}
test('Sauter ignore la version même après relecture et propose la suivante',async t=>{const f=await fixture(t);await f.choose('skip');assert.equal(f.store.read().skipped,'0.2.1');await f.control.check();assert.equal(f.panels.length,1);f.next('0.2.2');await f.control.check();assert.equal(f.panels.length,2);assert.equal(f.panels[1].messages[0].version,'0.2.2');});
test('Plus tard conserve la version et reporte seulement le rappel',async t=>{const f=await fixture(t);await f.choose('later');assert.equal(f.store.read().skipped,null);assert(f.store.read().remindAfter>Date.now());await f.control.check();assert.equal(f.panels.length,1);f.store.write({...f.store.read(),remindAfter:0});await f.control.check();assert.equal(f.panels.length,2);});
test('Installer vérifie, active puis redémarre sans ouvrir un installateur',async t=>{const f=await fixture(t);await f.choose('install');assert.equal(f.store.read().current,'0.2.1');assert.equal(f.store.read().pending,true);assert.equal(f.relaunch(),1);assert(f.panels[0].messages.some(s=>s.percent===100));});
