/* Application immersion. The online player keeps an explanatory dialog. */
window.initAppImmersion=function({audio,track,getVolume,AU_GENIUS_SYNC,move,startPlayback,canvasFor,clock,AU_LYRICS,createPublicLyricsView,renderLyrics}){
 const E=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
 const B=(label,fn)=>{const b=E('button','button secondary',label);b.type='button';b.onclick=fn;return b;};
 const app=['desktop','android','ios'].includes(document.documentElement.dataset.auApp);
 const d=E('dialog',app?'au-new-immersion':'au-dialog');d.id='auImmersionApp';d.setAttribute('aria-label','Écoute immersive');
 const close=B('Fermer',()=>d.close());close.setAttribute('aria-label','Fermer le mode immersion');
 let open;
 if(!app){const title=E('h2','','Mode immersion'),message=E('p','','Le mode immersion est exclusivement disponible dans les applications Avant l’usine pour Windows, Android et iPhone. Il n’est pas disponible sur les versions en ligne, sur PC ou mobile.');d.append(title,message,close);open=()=>d.showModal();}
 else{
  const head=E('header','au-im-head'),name=E('h2'),body=E('div','au-im-body'),art=E('section','au-im-art'),picture=E('div','au-im-picture'),lyrics=E('section','au-im-lyrics'),viewport=E('div','au-im-viewport'),note=E('p','au-im-note'),controls=E('footer','au-im-controls');
  lyrics.setAttribute('aria-label','Paroles du morceau');viewport.tabIndex=0;viewport.setAttribute('aria-label','Paroles défilantes');note.setAttribute('role','status');head.append(name,close);art.append(picture);lyrics.append(note,viewport);body.append(art,lyrics);d.append(head,body,controls);
  let source=null,signature='',coverKey=null,view=null,enabled=true,automatic=true,frame=0,coverURL=null,latest=new Map(),seeking=false,idleTimer=0,idleDeadline=0;
  function settleIdle(){clearTimeout(idleTimer);if(!d.open)return;const remaining=idleDeadline-performance.now();if(remaining>0){idleTimer=setTimeout(settleIdle,remaining);return;}d.classList.add('au-im-idle');tick();}
  function activity(){if(!d.open)return;d.classList.remove('au-im-idle');idleDeadline=performance.now()+10000;clearTimeout(idleTimer);idleTimer=setTimeout(settleIdle,10000);tick();}
  for(const event of ['pointermove','pointerdown','click','touchstart','keydown','wheel'])d.addEventListener(event,activity,{passive:true});
  const previous=B('⏮',()=>source?.move(-1)),play=B('Lire',()=>{if(!source)return;if(source.audio.paused)source.play().catch(e=>note.textContent=e.message);else source.audio.pause();}),next=B('⏭',()=>source?.move(1));previous.setAttribute('aria-label','Morceau précédent');next.setAttribute('aria-label','Morceau suivant');
  const lyricsButton=B('Masquer les paroles',()=>{enabled=!enabled;d.classList.toggle('au-im-no-lyrics',!enabled);lyrics.hidden=!enabled;lyricsButton.textContent=enabled?'Masquer les paroles':'Paroles';lyricsButton.setAttribute('aria-pressed',String(enabled));tick();});lyricsButton.setAttribute('aria-pressed','true');window.addEventListener('au:immersive-toggle-lyrics',()=>{if(d.open)lyricsButton.click();});const sizeCover=()=>{picture.style.width=Math.max(0,Math.min(art.clientWidth,art.clientHeight))+'px';};new ResizeObserver(sizeCover).observe(art);
  const follow=B('Défilement automatique : activé',()=>{automatic=!automatic;following();tick();});
  function following(){follow.textContent='Défilement automatique : '+(automatic?'activé':'en pause');follow.setAttribute('aria-pressed',String(automatic));}
  const seek=E('input'),times=E('span');seek.type='range';seek.min=0;seek.max=100;seek.step=.1;seek.setAttribute('aria-label','Position dans le morceau');
  seek.oninput=()=>{seeking=true;times.textContent=clock(+seek.value)+' / '+clock(source?.audio.duration);};seek.onchange=()=>{if(source&&Number.isFinite(source.audio.duration))source.audio.currentTime=Math.max(0,Math.min(source.audio.duration,+seek.value));seeking=false;tick();};
  controls.append(previous,play,next,lyricsButton,follow,seek,times);
  function pauseFollow(){automatic=false;following();}viewport.addEventListener('wheel',pauseFollow,{passive:true});viewport.addEventListener('touchstart',pauseFollow,{passive:true});viewport.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','Home','End','PageUp','PageDown'].includes(e.key))pauseFollow();});
  function current(){const local=window.AU_LOCAL_18?.player?.();if(local&&(!local.audio.paused||audio.paused&&!document.getElementById('local')?.hidden))return local;const t=track(),v=getVolume();return {key:v.number+':'+t?.number,title:t?.title||'Choisis un morceau',artist:t?.artist||'JuL',audio,plain:t?.lyrics||AU_GENIUS_SYNC.peek(v.number+':'+t?.number)||'',data:latest.get(v.number+':'+t?.number)||null,cover:v,play:()=>startPlayback(),move};}
  function dispose(){view?.dispose();view=null;}
  function cover(s){if(coverKey===s.cover)return;coverKey=s.cover;picture.querySelectorAll('video').forEach(v=>v.pause());picture.replaceChildren();if(coverURL){URL.revokeObjectURL(coverURL);coverURL=null;}if(s.local){const blob=s.cover?.blob;if(blob){coverURL=URL.createObjectURL(blob);const n=E(blob.type.startsWith('video/')?'video':'img');n.src=coverURL;if(n.tagName==='VIDEO'){n.loop=true;n.muted=true;n.playsInline=true;}else n.alt='Pochette — '+s.title;picture.append(n);}else picture.append(E('span','au-im-placeholder','♫'));}else if(s.cover){picture.append(canvasFor(s.cover,800));}}
  function rebuild(s){dispose();viewport.replaceChildren();const data=s.data,lines=data?.lines||AU_LYRICS.lines(s.plain||'');note.textContent=data?'Paroles synchronisées.':lines.length?'Paroles non synchronisées · défilement approximatif.':'Aucune parole disponible. Elles apparaîtront ici dès leur ajout.';follow.hidden=!lines.length;
   if(data){view=createPublicLyricsView(viewport,data,{automatic:()=>false,seek:time=>{s.audio.currentTime=time;tick();},endActions:false});viewport.classList.add('au-im-current-only');}
   else{viewport.classList.remove('au-lyrics-viewport','au-im-current-only');for(const line of lines)viewport.append(E('p','au-im-line',line));}viewport.scrollTop=0;
  }
  function refresh(){if(!d.open)return;const s=current(),key=s.key+'|'+JSON.stringify(s.data)+'|'+s.plain;const changed=source?.key!==s.key||source?.audio!==s.audio;source=s;name.textContent=s.title+' — '+s.artist;cover(s);if(key!==signature){signature=key;if(changed){automatic=true;following();}rebuild(s);}tick();}
  function tick(){if(!d.open||!source)return;const a=source.audio,length=Number.isFinite(a.duration)?a.duration:0;play.textContent=a.paused?'Lire':'Pause';seek.disabled=!length;seek.max=length||100;if(!seeking){seek.value=a.currentTime||0;times.textContent=clock(a.currentTime)+' / '+clock(length);}if(enabled&&!document.hidden){if(view){const active=view.paint(a.currentTime);view.rows.forEach((row,i)=>row.hidden=i!==active);}else if(automatic&&length){const intro=Math.min(8,length*.06),ratio=Math.max(0,Math.min(1,(a.currentTime-intro)/Math.max(1,length*.95-intro)));viewport.scrollTop=Math.max(0,viewport.scrollHeight-viewport.clientHeight)*ratio;}}for(const video of picture.querySelectorAll('video')){const on=!document.hidden&&document.documentElement.dataset.motion!=='off'&&document.documentElement.dataset.effects!=='off'&&!matchMedia('(prefers-reduced-motion: reduce)').matches;if(on&&video.paused)video.play().catch(()=>{});else if(!on)video.pause();}}
  function animate(){cancelAnimationFrame(frame);frame=0;if(!d.open||document.hidden)return;tick();if(source&&!source.audio.paused)frame=requestAnimationFrame(animate);}
  open=()=>{if(!d.open)d.showModal();signature='';refresh();renderLyrics();sizeCover();activity();animate();};
  for(const a of [audio,document.getElementById('localAudio')].filter(Boolean))for(const event of ['play','pause','timeupdate','seeked','loadedmetadata','durationchange','ended','emptied'])a.addEventListener(event,()=>{if(d.open){refresh();animate();}});
  window.addEventListener('au:sync-published',e=>{if(e.detail?.track){latest.set(e.detail.track,e.detail.data);refresh();}});window.addEventListener('au:lyrics-render',()=>queueMicrotask(refresh));window.addEventListener('au:local-player-change',refresh);document.addEventListener('visibilitychange',animate);window.addEventListener('resize',()=>{if(d.open)tick();});
  const lyricsFrame=document.getElementById('lyricsFrame');window.addEventListener('message',e=>{if(!d.open||source?.local||e.source!==lyricsFrame?.contentWindow||e.data?.request!==lyricsFrame.dataset.request||e.data?.type!=='avant-usine-sync-text'||typeof e.data.text!=='string'||e.data.text.length>40000)return;if(!source.data){source.plain=e.data.text;dispose();viewport.replaceChildren(...AU_LYRICS.lines(source.plain).map(line=>E('p','au-im-line',line)));note.textContent='Paroles non synchronisées · défilement approximatif.';follow.hidden=false;}});
  d.addEventListener('close',()=>{clearTimeout(idleTimer);d.classList.remove('au-im-idle');cancelAnimationFrame(frame);frame=0;dispose();signature='';picture.querySelectorAll('video').forEach(v=>v.pause());if(coverURL){URL.revokeObjectURL(coverURL);coverURL=null;coverKey=null;}});
 }
 document.body.append(d);const button=B('Immersion ⛶',open);button.className='lyrics-button au-immersive-open';document.querySelector('.dock-status')?.insertBefore(button,document.getElementById('status'));
 const localButton=B('Immersion ⛶',open);document.getElementById('localNow')?.after(localButton);
};
